package com.buslk.data

import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Repository interface defining operations for Lost and Found items.
 */
interface ILostAndFoundRepository {
    fun getLostAndFoundItemsStream(): Flow<Result<List<LostAndFoundDoc>>>
    suspend fun addLostAndFoundItem(item: LostAndFoundDoc): Result<Unit>
}

/**
 * Concrete implementation that connects natively to Firebase Firestore.
 */
class LostAndFoundRepository(
    private val firestore: FirebaseFirestore = FirebaseFirestore.getInstance()
) : ILostAndFoundRepository {

    private val collectionRef = firestore.collection("lost_and_found")

    /**
     * Creates a Hot Flow that actively listens to the Firestore collection.
     * When any item is added, updated, or removed, this flow automatically emits the fresh list.
     */
    override fun getLostAndFoundItemsStream(): Flow<Result<List<LostAndFoundDoc>>> = callbackFlow {
        // Order by timestamp descending (newest issues first)
        val listenerRegistration = collectionRef
            .orderBy("timestamp", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    trySend(Result.failure(error))
                    return@addSnapshotListener
                }

                if (snapshot != null) {
                    val items = snapshot.documents.mapNotNull { doc ->
                        doc.toObject(LostAndFoundDoc::class.java)?.copy(itemId = doc.id)
                    }
                    trySend(Result.success(items))
                } else {
                    trySend(Result.success(emptyList()))
                }
            }

        // Unregister the listener if the Flow consumer (ViewModel) is cancelled/destroyed
        awaitClose { listenerRegistration.remove() }
    }

    /**
     * Securely pushes a new Lost and Found report to the remote database.
     */
    override suspend fun addLostAndFoundItem(item: LostAndFoundDoc): Result<Unit> {
        return try {
            val documentRef = collectionRef.document() // Auto-generate ID
            // We overwrite the itemId field with the actual document ID generated by Firestore
            val itemToWrite = item.copy(itemId = documentRef.id)
            
            // await() suspends the coroutine until the network write completes
            documentRef.set(itemToWrite).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
