package com.buslk.data

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

/**
 * Data class representing a Trip document in Firestore.
 * Represents a historical journey made by a user.
 */
data class TripDoc(
    val tripId: String = "",
    val userId: String = "",
    val busId: String = "",
    val routeId: String = "",
    // Server timestamps generated by the system when a trip starts/ends
    @ServerTimestamp
    val startTime: Timestamp? = null,
    @ServerTimestamp
    val endTime: Timestamp? = null,
    // Denormalized strings populated at creation for fast reading without joins
    val startLocationName: String = "",
    val endLocationName: String = "",
    val distanceKm: Double = 0.0,
    val totalFare: Double = 0.0,
    val pointsEarned: Int = 0,
    val status: String = "ACTIVE" // ACTIVE, COMPLETED, CANCELLED
)
